network:
  version: 2
  ethernets:
    enp0s3:
      dhcp4: true
    enp0s8:
      dhcp4: false
      addresses:
        - 192.168.57.11/24
      routes:
        - to: 0.0.0.0/0
          via: 192.168.57.2
