network:
  version: 2
  ethernets:
    enp0s3:
      dhcp4: true
    enp0s8:
      dhcp4: false
      addresses:
        - 192.168.189.2/24
    enp0s9:
      dhcp4: false
      addresses:
        - 192.168.112.2/24
